#!/bin/bash

    #Функция выводит справку
    show()
    {
        echo "Использование: $(basename "$0") [ПАРАМЕТРЫ]"
        echo "Параметры:"
        echo " -u, —users Вывод списка пользователей и их домашних директорий, отсортированных по алфавиту."
        echo " -p, —processes Вывод списка запущенных процессов, отсортированных по их PID."
        echo " -l ПУТЬ, —log ПУТЬ Перенаправление стандартного вывода в файл, указанный по ПУТИ."
        echo " -e ПУТЬ, —errors ПУТЬ Перенаправление ошибок из stderr в файл, указанный по ПУТИ."
        echo " -h, —help Отображение этого сообщения справки и выход."
    }

    #Функция выводит список пользователей и их домашних директорий
    users()
    {
        cat /etc/passwd | awk -F: '{print $1 "\t" $6}' | sort
    }

    #Функция выводит список запущенных процессов
    processes()
    {
        ps -eo pid,cmd —sort=pid
    }

    #Функция добавляет вывод в файл
    output()
    {
        local path=$1
        shift
        "$@" > "$path"
    }

    #Функция перенаправляет ошибки в файл
    errors()
    {
        local path=$1
        shift
        "$@" 2> "$path"
    }

    #Цикл для ожидания ввода команды
    while true; do
    help
    read -p "Введите команду: " command

    case $command in
    -u|--users)
    users
    ;;
    -p|--processes)
    processes
    ;;
    -l|--log)
    read -p "Введите путь для лога: " log_path
    output "$log_path" "${@:3}"
    ;;
    -e|--errors)
    read -p "Введите путь для ошибок: " errors_path
    errors "$errors_path" "${@:3}"
    ;;
    -h|--help)
    help
    ;;
    *)
    echo "Неверная команда. Введите -h или —help для получения справки."
    ;;
    esac
    done
